name = "PlasticNetwork"
uuid = "e6ec0278-4638-400e-9a0a-44f84d13db8f"
authors = ["Ahmad Izzuddin"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
